### ISSUE TITLE
Jetbrains Support

### ISSUE THREAD

**Issue by furesoft** [AvaloniaUI/TemplateStudio#13]
### Is your feature request related to a problem? Please describe.

I only use Jetbrains Rider for developement

### Describe the solution you'd like

A Jetbrains Rider Extension

**Comment by Mrxx99** [comment]
You can install the avalonia CLI templates, they will show up in Rider: https://docs.avaloniaui.net/docs/next/get-started/install

Although Rider currently does not show the parameters of these templates (yet), you can raise your vote for this here: https://youtrack.jetbrains.com/issue/RIDER-16759/Support-parameters-in-custom-project-templates

**Comment by maxkatz6** [comment]
Yes, we recommend using CLI templates for Rider.
