### ISSUE TITLE
Unable to create new Avalonia project on Visual Studio 2022 Pro.

### ISSUE THREAD

**Issue by submaie** [AvaloniaUI/TemplateStudio#24]
### Describe the bug

In Visual Studio Professional 2022 ver 17.7.1 a template error msg is displayed when attempting to create a C# Avalonia application.
![ScreenShot](https://github.com/AvaloniaUI/TemplateStudio/assets/31879920/30aab9c8-bb27-44dc-900f-c41e4efb9d39)

### To Reproduce

 1. create a new solution.
 2. Click "Create" button.
 3. In "New Avalonia app" form, follow the wizard's instructions to select project options.

### Additional context

System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Microsoft.Templates.Core.Gen.GenController.ValidateUserSelection(UserSelection userSelection, Boolean isNewProject)
   在 Microsoft.Templates.Core.Gen.NewProjectGenController.<UnsafeGenerateProjectAsync>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.Templates.UI.Services.GenerationService.<GenerateProjectAsync>d__5.MoveNext()

### About your setup

 - Visual Studio Version:  Professional 2022 17.7.1
 - Template Studio Wizard Version: 1.3
 - Windows Build: 22H2 22621.2283

**Comment by okichallenge** [comment]
Maybe your version doesn't match，uTry upgrading to 17.7.5。I upgraded from 17.0.1 to 17.7.5 to solve this similar problem。
