### ISSUE TITLE
Unable to create new Avalonia project on Visual Studio Preview

### ISSUE THREAD

**Issue by MarkBrainfire** [AvaloniaUI/TemplateStudio#25]
**Describe the bug**
In Visual Studio Version 17.8 Preview 1.0 a template error msg is displayed when attempting to create a C# Avalonia application.

**To Reproduce**
Use Visual Studio Verion 17.8 Preview 1.0 to attempt to create a new solution.
When you press "Create" the error will be displayed.

**Work Around**
Use the current stable version of Visual Studio.

**Screenshots**
![Avalonia Error](https://github.com/AvaloniaUI/Avalonia/assets/78389339/34eac77d-b355-41c0-9186-0f9603931e14)

**Comment by Takoooooo** [comment]
Blocked by dependency,currently,my only advice is to downgrade to 17.7 ;(
