### ISSUE TITLE
Unable to Build Template Studio after checking out the demo

### ISSUE THREAD

**Issue by CartBlanche** [AvaloniaUI/TemplateStudio#29]
### Describe the bug

I checked out the project and was Unable to Build Template Studio from the source code provided with the following errors:

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0246	The type or namespace name 'CERTENROLLLib' could not be found (are you missing a using directive or an assembly reference?)	TemplateStudioForAvalonia	C:\Users\savag\Downloads\TemplateStudio-main\code\SharedFunctionality.Core\Utilities\CertificateService.cs	6	Active	
Error	CS0246	The type or namespace name 'CX509CertificateRequestCertificate' could not be found (are you missing a using directive or an assembly reference?)	TemplateStudioForAvalonia	C:\Users\savag\Downloads\TemplateStudio-main\code\SharedFunctionality.Core\Utilities\CertificateService.cs	66	Active	
Error	CS0246	The type or namespace name 'CX509CertificateRequestCertificate' could not be found (are you missing a using directive or an assembly reference?)	TemplateStudioForAvalonia	C:\Users\savag\Downloads\TemplateStudio-main\code\SharedFunctionality.Core\Utilities\CertificateService.cs	77	Active	
Error	CS0246	The type or namespace name 'CX509CertificateRequestCertificate' could not be found (are you missing a using directive or an assembly reference?)	TemplateStudioForAvalonia	C:\Users\savag\Downloads\TemplateStudio-main\code\SharedFunctionality.Core\Utilities\CertificateService.cs	91	Active	
Error	CS0246	The type or namespace name 'CX509CertificateRequestCertificate' could not be found (are you missing a using directive or an assembly reference?)	TemplateStudioForAvalonia	C:\Users\savag\Downloads\TemplateStudio-main\code\SharedFunctionality.Core\Utilities\CertificateService.cs	102	Active	

Is the repo missing something or am I?

### To Reproduce

 1. Checkout the AvaloniaUI/TemplateStudio repo
 2. Load the .sln
 3. Try to build it.

### About your setup

 - Visual Studio Version:  
Microsoft Visual Studio Professional 2022
Version 17.8.5
VisualStudio.17.Release/17.8.5+34511.84
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA098
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.8.358.6298
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.8.358.6298
Azure App Service Tools v3.0.0

C# Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.8.17 (957fbed)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.8.3.2405201+d135dd8d2ec1c2fbdee220e8656b308694e17a4b
Provides languages services for ASP.NET Core Razor.

TypeScript Tools   17.0.20920.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.8.0-beta.23475.2+10f956e631a1efc0f7f5e49c626c494cd32b1f50
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Unity   17.8.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VS Tools for Meadow   1.0
Tools for developing Meadow Applications

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.8.0.157 (d17-8@8e82278)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.8.3.6 (remotes/origin/d17-8@eccf46a291)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

 - Windows Build: 
 Edition	Windows 11 Pro
Version	22H2
Installed on	‎12/‎08/‎2023
OS build	22621.3007
Serial number	5CG3161P2F
Experience	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by maxkatz6** [comment]
Using "DebugWpf" or "ReleaseWpf" configurations and running [TemplateStudioForAvalonia.csproj](https://github.com/AvaloniaUI/TemplateStudio/blob/1.4/code/TemplateStudioForAvalonia/TemplateStudioForAvalonia.csproj) works. Everything else seems to be part of the upstream winui/uwp template studio.
