### ISSUE TITLE
Update to .NET 8

### ISSUE THREAD

**Issue by josago97** [AvaloniaUI/TemplateStudio#32]
### Is your feature request related to a problem? Please describe.

The templates use the .net 7 version, which is short-lived. The most recent stable version is .NET 8.

**Comment by nich2408** [comment]
I think the template should also target the latest avalonia nuget packages.
For example if you later set target to net8.0 in the Browser project without upgrading the packages it won't run.

**Comment by maxkatz6** [comment]
Done, .NET 8 and 11.1
